### ISSUE TITLE
Unable to customize styling.

### ISSUE THREAD

**Issue by wiseaidev** [sweetalert2/sweetalert2-react-content#209]
Hello there. I am trying to define and apply some CSS rules on a `Swal.fire` instance. For example, the following alert text looks off position, so I want to center it with the icon.

![Screenshot from 2022-08-19 23-50-37](https://user-images.githubusercontent.com/62179149/185707476-7e7710ab-bdfa-46d7-b66b-65fd3e64607f.png)

The react component I have created:

```javascript
import React from 'react';
import Swal from 'sweetalert2';
import withReactContent from 'sweetalert2-react-content';
import { Box } from '@mui/material';
import "./style.css"

const MySwal = withReactContent(Swal);

const CustomSweetAlert = ({content, variant, delay}) => {
  const sweetAlerts = (content, variant, delay) => {
    MySwal.fire({
      icon: variant,
      text: content,
      background: "white",
      color: "black",
      position: 'top-end',
      toast: true,
      showCancelButton: false,
      showConfirmButton: false,
      timer: delay,
      timerProgressBar: true,
      didOpen: (toast) => {
        toast.addEventListener('mouseenter', Swal.stopTimer)
        toast.addEventListener('mouseleave', Swal.resumeTimer)
      },
    });
  };
  return (
    <Box className="alert-box">
      {sweetAlerts(content, variant, delay)}
    </Box>
  );
};

export default CustomSweetAlert;
```

CSS rules:

```css
.swal2-timer-progress-bar-container .swal2-timer-progress-bar {
    background-color: black;
    color: black;
}
.swal2-popup .swal2-html-container {
    text-align: center;
    border: 1px solid red;
}
.alert-box{
    text-align: center;
    border: 1px solid red;
}
```

As you may probably guess, the class names were taken using inspect element:

![Screenshot from 2022-08-20 00-12-00](https://user-images.githubusercontent.com/62179149/185707940-cf5c0dd0-39e5-4c52-bea7-cfa2ea92df2c.png)
![Screenshot from 2022-08-20 00-12-09](https://user-images.githubusercontent.com/62179149/185707949-1ba6e458-9381-41c9-b13c-d0acec7bdb02.png)

That's pretty much it, I am wondering how to apply custom styles on these elements.

### Edit

I have read [the docs](https://sweetalert2.github.io/), but, unfortunately, didn't find any mention about text alignment and stuff.

### Edit1

Found the issue, there is some element that sets the display property to `grid`, changed it in the browser seems to fix the issue:

![Screenshot from 2022-08-20 00-36-22](https://user-images.githubusercontent.com/62179149/185710869-072969eb-9ae9-4526-a732-7803810d364c.png)

![Screenshot from 2022-08-20 00-36-36](https://user-images.githubusercontent.com/62179149/185710874-be5b419e-121a-45ff-ae76-c4d9b39e3375.png)

However, the changes don't reflect if i define it in a custom CSS file:

```css
.swal2-popup {
  display: flex;
}
.alert-box {
  display: flex;
}
```

Not sure what's wrong.
