### ISSUE TITLE
Backdrop doesn't cover entire of screen

### ISSUE THREAD

**Issue by memcaliber** [sweetalert2/sweetalert2-react-content#244]
**Describe the bug**

Hi.. i try this version on my nextJS theme. all function works fine, but when alert appears, the black background/backdrop doesn't cover entire of screen/page area. my sidebar menu not covered at all.
![bug reac sweetalert](https://github.com/sweetalert2/sweetalert2-react-content/assets/17555144/c589388e-1144-45af-b58f-cbe72856e993)

**Comment by limonte** [comment]
```js
Swal.fire({
  ...
  customClass: {
    container: 'custom-z-index',
  }
})
```

```css
.custom-z-index {
  z-index: 9999; /* z-index is 1060 by default, for your project make it bigger than z-index of sidebar */
}
```
